version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: wifi_user
      POSTGRES_PASSWORD: wifi_pass
      POSTGRES_DB: wifi_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wifi_user -d wifi_db']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://wifi_user:wifi_pass@db:5432/wifi_db
    restart: always

volumes:
  db_data:
