version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: wifi_user
      POSTGRES_PASSWORD: wifi_pass
      POSTGRES_DB: wifi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env # Aquí cargamos el archivo .env

volumes:
  db_data:
